sudo: required
dist: trusty
language: cpp
language: php

compiler:
    - gcc

php:
    - '5.6'
    - '7.2'

before_install:
    - php --ini
    - sudo add-apt-repository -y ppa:kojoley/boost
    - sudo apt-get update -y || echo "update error"
    - lsb_release -a

install:
    - git clone https://github.com/yyzybb537/Boost-dev-bin.git /tmp/boost-dev-bin && sudo dpkg -i /tmp/boost-dev-bin/libboost1.59-all-dev.deb
    - ls /usr/local/lib/libboost*
    - sudo ldconfig
    - sudo apt-get install -y -qq cmake 
    - git clone https://github.com/yyzybb537/libgo /tmp/libgo
    - pushd .
    - cd /tmp/libgo && mkdir build && cd build
    - sudo rm * -rf && cmake .. -DENABLE_BOOST_CONTEXT=ON && make -j4 && sudo make install
    - sudo ldconfig

script: 
    - popd
    - phpize
    - ./configure --with-php-config=`which php-config`
    - make clean && cat Makefile && make && make install
    - echo "extension=phpgo.so" > `php --ini | grep "Scan for additional" | awk '{print $7 "/phpgo.ini"}'`
    - export TEST_PHP_EXECUTABLE=./test_php 
    - php run-tests.php tests | grep failed | awk '{print $3}'

after_success:
    - 

branches:
    only:
    - dev
    - master

notifications:
  email: true
